// Plain-language glossary. Written for learning, not as reference: each entry says
// what the thing is, gives an everyday analogy, and why it matters for security.
// `match` finds the term inside module theory; module membership is derived from
// where each term actually appears in /content, never assigned by hand.

export type GlossaryEntry = {
  id: string;
  term: string;
  match: RegExp;
  short: string;
  analogy: string;
  why: string;
  /** Layer (frontmatter `layer`) whose module should host this star when several discuss it. */
  layer?: string;
};

export const GLOSSARY: GlossaryEntry[] = [
  {
    id: "ipv4",
    term: "IPv4",
    match: /\bIPv4\b/,
    short: "El sobre de cada paquete: dirección de origen, de destino y unas cuantas instrucciones de entrega, en 20 bytes.",
    analogy: "Como el sobre de una carta: el cartero sólo mira el sobre, nunca abre la carta.",
    why: "Casi todas las reglas de firewall deciden mirando campos de esta cabecera.",
  },
  {
    id: "ttl",
    term: "TTL",
    layer: "L3/L4",
    match: /\bTTL\b/,
    short: "Contador de saltos que baja en 1 en cada router. Si llega a 0, el paquete se tira y se avisa con ICMP Time Exceeded.",
    analogy: "Una patata caliente que sólo puede pasar de mano en mano N veces antes de caerse.",
    why: "Evita bucles infinitos; traceroute lo usa para descubrir cada router del camino.",
  },
  {
    id: "cidr",
    term: "CIDR",
    match: /\bCIDR\b/,
    short: "Forma de escribir un rango de direcciones: 10.44.0.0/24 son las 256 direcciones que comparten los primeros 24 bits.",
    analogy: "Como un código postal: /16 es la ciudad entera, /24 es una calle.",
    why: "Un rango dice hasta dónde llega algo, no quién tiene permiso. Confiar en «es de mi red» es el error clásico.",
  },
  {
    id: "checksum",
    term: "Checksum",
    match: /\bchecksum\b/i,
    short: "Número calculado a partir de los bytes de la cabecera para detectar si se corrompió por el camino.",
    analogy: "La suma de control de una cuenta bancaria: si un dígito cambia, la cuenta no cuadra.",
    why: "Cualquier cambio (TTL, NAT) obliga a recalcularlo; en capturas locales puede parecer «malo» por offload.",
  },
  {
    id: "tcp",
    term: "TCP",
    match: /\bTCP\b/,
    short: "Protocolo que convierte paquetes sueltos en una conversación fiable y ordenada entre dos puertos.",
    analogy: "Una llamada de teléfono: primero se establece, se confirma lo que se oye y al final se cuelga.",
    why: "Su estado (conexión nueva o establecida) es lo que usan los firewalls stateful para decidir.",
  },
  {
    id: "handshake",
    term: "Handshake SYN",
    match: /\bSYN\b|handshake/i,
    short: "Apertura de TCP en tres pasos: SYN («¿hablamos?»), SYN-ACK («sí»), ACK («perfecto»).",
    analogy: "«¿Me oyes?» — «Te oigo, ¿me oyes tú?» — «Sí».",
    why: "Si mandas SYN y no vuelve nada: probablemente DROP. Si vuelve RST: el host está, pero nadie escucha ese puerto.",
  },
  {
    id: "udp",
    term: "UDP",
    match: /\bUDP\b/,
    short: "Protocolo sin conexión: manda datagramas y no confirma nada. Rápido y simple.",
    analogy: "Una postal: la echas al buzón y no sabes si llegó.",
    why: "Una política que sólo filtra TCP deja UDP abierto; DNS viaja casi siempre por UDP/53.",
  },
  {
    id: "icmp",
    term: "ICMP",
    match: /\bICMP\b/,
    short: "Mensajes de control de la red: «destino inalcanzable», «tiempo excedido», ping.",
    analogy: "Los avisos de Correos: «dirección desconocida», «devuelto al remitente».",
    why: "Bloquearlo del todo rompe diagnósticos y el descubrimiento de MTU; permitirlo todo facilita reconocimiento.",
  },
  {
    id: "fragment",
    term: "Fragmentación",
    match: /fragment/i,
    short: "Partir un paquete grande en trozos cuando no cabe en el enlace. Sólo el primer trozo lleva la cabecera TCP/UDP.",
    analogy: "Mandar un mueble en varias cajas: sólo la primera caja lleva la etiqueta con el contenido.",
    why: "Un filtro que no reensambla puede dejar pasar los trozos siguientes sin ver el puerto.",
  },
  {
    id: "routing",
    term: "Ruta / longest-prefix",
    layer: "L3/L4",
    match: /longest-prefix|\bruta\b/i,
    short: "El kernel elige por dónde enviar un paquete buscando la ruta más específica (el prefijo más largo) que contiene el destino.",
    analogy: "Si tienes indicaciones para «Madrid» y para «Calle Mayor, Madrid», usas las más concretas.",
    why: "Activar ip_forward no crea rutas ni permisos: sólo permite reenviar.",
  },
  {
    id: "netns",
    term: "Network namespace",
    match: /\bnetns\b|namespace/i,
    short: "Una copia aislada de la red del kernel: sus propias interfaces, rutas, puertos y firewall.",
    analogy: "Un piso dentro de un edificio: cada uno con su puerta, su buzón y sus normas.",
    why: "Es la base del aislamiento de contenedores y pods.",
  },
  {
    id: "veth",
    term: "veth",
    match: /\bveth\b/i,
    short: "Un cable virtual con dos extremos: lo que entra por uno sale por el otro. Conecta un namespace con el exterior.",
    analogy: "Un tubo neumático entre dos habitaciones.",
    why: "Si capturas tráfico en la interfaz equivocada, no ves nada: hay que saber en qué extremo mirar.",
  },
  {
    id: "bridge",
    term: "Bridge",
    match: /\bbridge\b/i,
    short: "Un switch virtual en Linux: aprende qué MAC hay detrás de cada puerto y reenvía tramas en capa 2.",
    analogy: "Una centralita que aprende en qué despacho está cada persona.",
    why: "Trabaja en L2: no autoriza nada por IP, así que por sí solo permite movimiento lateral.",
  },
  {
    id: "mac",
    term: "MAC / FDB",
    match: /\bMAC\b|\bFDB\b/,
    short: "La MAC es la dirección física de una interfaz; la FDB es la tabla donde el bridge apunta dónde vio cada MAC.",
    analogy: "La agenda de la centralita: «Ana está en la extensión 3».",
    why: "Si una MAC desconocida aparece, el bridge inunda la trama a todos los puertos.",
  },
  {
    id: "netfilter",
    term: "Netfilter / iptables",
    match: /Netfilter|iptables|nftables|PREROUTING|FORWARD/,
    short: "El sistema de ganchos del kernel donde se filtra, se traduce (NAT) y se marca el tráfico. iptables y nftables lo configuran.",
    analogy: "Los controles de un aeropuerto: llegada, tránsito y salida, cada uno con su mostrador.",
    why: "El orden de las reglas importa: una regla que permite antes hace inalcanzable una que deniega después.",
  },
  {
    id: "conntrack",
    term: "conntrack",
    layer: "Kernel",
    match: /[Cc]onntrack|ESTABLISHED|stateful/,
    short: "La memoria del kernel sobre conexiones en curso: permite aceptar respuestas de conexiones que tú iniciaste.",
    analogy: "El portero que recuerda que saliste hace un rato y te deja volver a entrar.",
    why: "La tabla es finita: llenarla es una forma de denegación de servicio.",
  },
  {
    id: "nat",
    term: "NAT (SNAT/DNAT)",
    match: /\bNAT\b|SNAT|DNAT|MASQUERADE/,
    short: "Reescribir direcciones: SNAT cambia el origen (salir a Internet), DNAT cambia el destino (publicar un servicio).",
    analogy: "Una centralita que llama por ti: el otro lado ve el número de la empresa, no tu extensión.",
    why: "Con NAT los logs pierden la IP real del cliente: la identidad por IP se degrada.",
  },
  {
    id: "drop-reject",
    term: "DROP vs REJECT",
    match: /\bDROP\b|\bREJECT\b/,
    short: "DROP descarta en silencio (el cliente espera hasta agotar el tiempo); REJECT responde con un error.",
    analogy: "No contestar una llamada frente a colgar diciendo «aquí no es».",
    why: "DROP da menos información a un atacante; REJECT hace que los fallos legítimos sean más rápidos de diagnosticar.",
  },
  {
    id: "dns",
    term: "DNS",
    match: /\bDNS\b/,
    short: "Traduce nombres (api.internal) a direcciones IP. Consulta por UDP/53 y recurre a TCP/53 en respuestas grandes.",
    analogy: "La agenda de contactos del teléfono.",
    why: "Si bloqueas DNS, todo parece caído; si lo dejas libre, es un canal de salida de datos.",
  },
  {
    id: "tls",
    term: "TLS",
    match: /\bTLS\b/,
    short: "Cifra y autentica una conexión: el cliente comprueba que el servidor es quien dice ser mediante su certificado.",
    analogy: "Un sobre lacrado con el sello oficial de quien lo envía.",
    why: "Desactivar la verificación («skip verify») deja el cifrado sin saber con quién hablas.",
  },
  {
    id: "x509",
    term: "Certificado X.509",
    match: /X\.509|certificad|\bSAN\b|\bCA\b/,
    short: "Documento firmado por una CA que une una clave pública con una identidad (nombres en el campo SAN).",
    analogy: "Un DNI: foto (clave), nombre (SAN) y el sello de quien lo expide (CA).",
    why: "Hay que validar cadena, fechas y que el nombre coincide; una CA demasiado amplia confía en demasiado.",
  },
  {
    id: "sni",
    term: "SNI",
    match: /\bSNI\b/,
    short: "El nombre del servidor que el cliente pide al empezar TLS, para que el servidor elija qué certificado mostrar.",
    analogy: "Decir en recepción a qué empresa del edificio vienes.",
    why: "Sólo selecciona; no autentica a nadie.",
  },
  {
    id: "mtls",
    term: "mTLS",
    match: /\bmTLS\b/,
    short: "TLS en el que ambos lados presentan certificado: el servidor también comprueba quién es el cliente.",
    analogy: "Dos personas enseñándose el DNI mutuamente antes de hablar.",
    why: "Base de Zero Trust entre servicios: se autoriza la identidad, no la IP.",
  },
  {
    id: "spiffe",
    term: "SPIFFE",
    match: /SPIFFE|SVID|spiffe:/,
    short: "Estándar de identidad para workloads: cada servicio recibe un ID tipo spiffe://dominio/ns/prod/sa/api y un certificado corto.",
    analogy: "Una acreditación con foto que caduca cada pocas horas y se renueva sola.",
    why: "Permite escribir políticas como «sólo api habla con db», independientemente de su IP.",
  },
  {
    id: "pod",
    term: "Pod",
    match: /\bPods?\b/,
    short: "La unidad mínima de Kubernetes: uno o varios contenedores que comparten namespace de red e IP.",
    analogy: "Un piso compartido: varios inquilinos, una sola dirección postal.",
    why: "Las IPs de pods son efímeras: una política basada en IP se queda obsoleta.",
  },
  {
    id: "cni",
    term: "CNI",
    match: /\bCNI\b/,
    short: "El plugin que da red a cada pod: crea la interfaz, asigna la IP y pone las rutas. También aplica las NetworkPolicies.",
    analogy: "El electricista que conecta cada piso nuevo a la red del edificio.",
    why: "Sin un CNI que las aplique, las NetworkPolicies existen pero no hacen nada.",
  },
  {
    id: "vxlan",
    term: "VXLAN / MTU",
    match: /VXLAN|\bMTU\b/,
    short: "VXLAN mete el tráfico de los pods dentro de otro paquete para cruzar entre nodos; esa envoltura ocupa bytes y reduce la MTU.",
    analogy: "Meter una caja dentro de otra caja: el contenido útil tiene que ser más pequeño.",
    why: "Una MTU mal alineada causa fallos raros: lo pequeño funciona y lo grande se cuelga.",
  },
  {
    id: "service",
    term: "Service / ClusterIP",
    match: /ClusterIP|\bService\b|kube-proxy/,
    short: "Una IP virtual estable que reparte tráfico entre pods; kube-proxy la implementa reescribiendo el destino (DNAT).",
    analogy: "La centralita de una empresa: un único número que te pasa con quien esté libre.",
    why: "Un Service no es un firewall ni una identidad: no autoriza a nadie.",
  },
  {
    id: "nodeport",
    term: "NodePort",
    match: /NodePort/,
    short: "Abre el mismo puerto en todos los nodos del clúster para llegar a un Service desde fuera.",
    analogy: "Poner una puerta a la calle en cada edificio del barrio.",
    why: "Aumenta mucho la superficie expuesta.",
  },
  {
    id: "netpol",
    term: "NetworkPolicy",
    match: /NetworkPolicy|default deny|policyTypes/,
    short: "Regla de Kubernetes que dice qué pods pueden hablar con cuáles. Con Ingress+Egress y sin reglas, deniega todo.",
    analogy: "La lista de invitados de cada fiesta.",
    why: "Con default deny también bloqueas el DNS: hay que permitir UDP/TCP 53 explícitamente.",
  },
  {
    id: "ebpf",
    term: "eBPF",
    match: /eBPF/,
    short: "Pequeños programas que se cargan en el kernel, se verifican antes de ejecutarse y se enganchan a eventos (paquetes, llamadas…).",
    analogy: "Instalar sensores dentro del motor sin tener que desmontarlo.",
    why: "Da visibilidad y control finos; un programa cargado sin inventario es también un punto ciego.",
  },
  {
    id: "verifier",
    term: "Verifier",
    match: /[Vv]erifier/,
    short: "El revisor del kernel que comprueba que un programa eBPF es seguro (termina, no lee memoria indebida) antes de admitirlo.",
    analogy: "La ITV antes de dejar circular un coche.",
    why: "Si rechaza tu programa, es que no pudo demostrar un acceso seguro.",
  },
  {
    id: "xdp",
    term: "XDP",
    match: /\bXDP\b/,
    short: "Gancho eBPF en el punto más temprano de recepción, antes de la pila de red: puede tirar o redirigir paquetes muy rápido.",
    analogy: "Un control en la misma puerta del edificio, antes de recepción.",
    why: "Al ir antes que iptables/conntrack, puede saltarse esas reglas sin que lo notes.",
  },
  {
    id: "tc",
    term: "TC hook",
    match: /(?<![/\w])TC(?![=/\w])/,
    short: "Gancho eBPF en la interfaz (entrada o salida), después de XDP, útil para políticas y telemetría por veth de pod.",
    analogy: "Un control en el pasillo de cada piso.",
    why: "Permite ver y filtrar tráfico por contenedor.",
  },
  {
    id: "bpfmap",
    term: "Mapa eBPF",
    match: /[Mm]apas?\b/,
    short: "Almacén clave-valor compartido entre programas eBPF y el espacio de usuario (contadores, listas de bloqueo…).",
    analogy: "Una pizarra compartida donde los sensores apuntan lo que ven.",
    why: "Los mapas «pinned» sobreviven al programa que los creó: hay que inventariarlos.",
  },
  {
    id: "vpc",
    term: "VPC / subred",
    match: /\bVPC\b|subred/i,
    short: "Tu red privada en la nube, dividida en subredes con sus propias tablas de rutas.",
    analogy: "Un recinto vallado con zonas: recepción, oficinas y cámara acorazada.",
    why: "Sólo el borde debe tener acceso a Internet; datos y aplicación, sin IP pública.",
  },
  {
    id: "sg",
    term: "Security Group",
    match: /Security Group|\bSG\b/,
    short: "Firewall stateful asociado a cada interfaz en la nube: si permites la entrada, la respuesta sale sola.",
    analogy: "Un portero por puerta que recuerda a quién dejó entrar.",
    why: "Mejor referenciar otro SG («desde sg-api») que un CIDR amplio.",
  },
  {
    id: "nacl",
    term: "NACL",
    match: /\bNACL\b/,
    short: "Lista de control stateless por subred: hay que permitir ida y vuelta, incluidos los puertos efímeros de respuesta.",
    analogy: "Una barrera en la entrada del barrio que no recuerda quién salió.",
    why: "Olvidar los puertos efímeros rompe las respuestas; allow-all anula la barrera.",
  },
  {
    id: "zerotrust",
    term: "Zero Trust",
    match: /Zero Trust/,
    short: "Principio de no confiar en nada por estar «dentro» de la red: cada conexión se autentica y autoriza por identidad y contexto.",
    analogy: "Enseñar la acreditación en cada puerta, no sólo al entrar al edificio.",
    why: "Red privada no significa confiable.",
  },
  {
    id: "planes",
    term: "Control / data plane",
    match: /[Cc]ontrol plane|[Dd]ata plane/,
    short: "El control plane decide y reparte identidades y políticas; el data plane las aplica en cada conexión.",
    analogy: "La dirección que escribe las normas frente a los vigilantes que las hacen cumplir.",
    why: "Separarlos permite rotar identidades sin tocar el tráfico.",
  },
  {
    id: "endpoint",
    term: "Private endpoint",
    match: /[Pp]rivate endpoint|[Ee]ndpoint privado/,
    short: "Acceso a un servicio cloud por la red privada, sin pasar por Internet.",
    analogy: "Un pasillo interno hasta el banco en vez de salir a la calle.",
    why: "Evita el tránsito público, pero no autentica a quien llama.",
  },
];

export function conceptsIn(text: string): GlossaryEntry[] {
  return GLOSSARY.map((g) => ({ g, at: text.search(g.match) }))
    .filter((x) => x.at >= 0)
    .sort((a, b) => a.at - b.at)
    .map((x) => x.g);
}

export function countIn(text: string, g: GlossaryEntry): number {
  return text.match(new RegExp(g.match.source, g.match.flags.includes("g") ? g.match.flags : g.match.flags + "g"))?.length ?? 0;
}
